version: "3"
services:
  benzaiten:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace
    working_dir: /workspace
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
