name: PyTest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker Build
        run: docker-compose build
      - name: Docker Compose Up
        run: docker-compose up -d
      - name: Pipenv Install
        run: docker-compose exec -T app pipenv install
      - name: Pipenv Run Pytest
        run: docker-compose exec -T app pipenv run pytest
