name: Run pytest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker compose -f docker/docker-compose.test.yml build
      - name: Run Pytest
        run:
          docker compose -f docker/docker-compose.test.yml run --rm -T benzaiten
          make tests
