name: Run pytest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker Build
        run: docker compose -f docker/docker-compose.test.yaml build
      - name: Docker Compose Up
        run: docker compose -f docker/docker-compose.test.yaml up -d
      - name: Run Pytest
        run:
          docker compose -f docker/docker-compose.test.yaml exec -T benzaiten
          pytest
